version: '3'

services:  
  client:
    container_name: front 
    build: "./client"    
    tty: true
    volumes:
      - "./client"
    volumes:
      - './client:/fb-front'
      - '/fb-front/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - fibapp
  api:  
    build: "."
    container_name: api 
    volumes:
      - '.:/fb-back'
      - '/fb-back/node_modules'
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - fibapp
  db:
    image: mysql:latest        
    container_name: db
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_DATABASE=fibonaccy"
      # - "PMA_HOST=fibdb"
    ports:
      - "3306:3306"
    networks:
      - fibapp


networks:
  fibapp:
    driver: bridge 
  